var speechLangs = [
    {lang: 'Afrikaans (South Africa)', langCode: 'af-ZA'},
    {lang: 'Albanian (Albania)', langCode: 'sq-AL'},
    {lang: 'Amharic (Ethiopia)', langCode: 'am-ET'},
    {lang: 'Arabic (Algeria)', langCode: 'ar-DZ'},
    {lang: 'Arabic (Bahrain)', langCode: 'ar-BH'},
    {lang: 'Arabic (Egypt)', langCode: 'ar-EG'},
    {lang: 'Arabic (Iraq)', langCode: 'ar-IQ'},
    {lang: 'Arabic (Israel)', langCode: 'ar-IL'},
    {lang: 'Arabic (Jordan)', langCode: 'ar-JO'},
    {lang: 'Arabic (Kuwait)', langCode: 'ar-KW'},
    {lang: 'Arabic (Lebanon)', langCode: 'ar-LB'},
    {lang: 'Arabic (Morocco)', langCode: 'ar-MA'},
    {lang: 'Arabic (Oman)', langCode: 'ar-OM'},
    {lang: 'Arabic (Qatar)', langCode: 'ar-QA'},
    {lang: 'Arabic (Saudi Arabia)', langCode: 'ar-SA'},
    {lang: 'Arabic (State of Palestine)', langCode: 'ar-PS'},
    {lang: 'Arabic (Tunisia)', langCode: 'ar-TN'},
    {lang: 'Arabic (United Arab Emirates)', langCode: 'ar-AE'},
    {lang: 'Arabic (Yemen)', langCode: 'ar-YE'},
    {lang: 'Armenian (Armenia)', langCode: 'hy-AM'},
    {lang: 'Azerbaijani (Azerbaijan)', langCode: 'az-AZ'},
    {lang: 'Basque (Spain)', langCode: 'eu-ES'},
    {lang: 'Bengali (Bangladesh)', langCode: 'bn-BD'},
    {lang: 'Bengali (India)', langCode: 'bn-IN'},
    {lang: 'Bosnian (Bosnia and Herzegovina)', langCode: 'bs-BA'},
    {lang: 'Bulgarian (Bulgaria)', langCode: 'bg-BG'},
    {lang: 'Burmese (Myanmar)', langCode: 'my-MM'},
    {lang: 'Catalan (Spain)', langCode: 'ca-ES'},
    {lang: 'Chinese, Cantonese (Traditional Hong Kong)', langCode: 'yue-Hant-HK'},
    {lang: 'Chinese, Mandarin (Simplified, China)', langCode: 'zh'},
    {lang: 'Chinese, Mandarin (Traditional, Taiwan)', langCode: 'zh-TW'},
    {lang: 'Croatian (Croatia)', langCode: 'hr-HR'},
    {lang: 'Czech (Czech Republic)', langCode: 'cs-CZ'},
    {lang: 'Danish (Denmark)', langCode: 'da-DK'},
    {lang: 'Dutch (Belgium)', langCode: 'nl-BE'},
    {lang: 'Dutch (Netherlands)', langCode: 'nl-NL'},
    {lang: 'English (Australia)', langCode: 'en-AU'},
    {lang: 'English (Canada)', langCode: 'en-CA'},
    {lang: 'English (Ghana)', langCode: 'en-GH'},
    {lang: 'English (Hong Kong)', langCode: 'en-HK'},
    {lang: 'English (India)', langCode: 'en-IN'},
    {lang: 'English (Ireland)', langCode: 'en-IE'},
    {lang: 'English (Kenya)', langCode: 'en-KE'},
    {lang: 'English (New Zealand)', langCode: 'en-NZ'},
    {lang: 'English (Nigeria)', langCode: 'en-NG'},
    {lang: 'English (Pakistan)', langCode: 'en-PK'},
    {lang: 'English (Philippines)', langCode: 'en-PH'},
    {lang: 'English (Singapore)', langCode: 'en-SG'},
    {lang: 'English (South Africa)', langCode: 'en-ZA'},
    {lang: 'English (Tanzania)', langCode: 'en-TZ'},
    {lang: 'English (United Kingdom)', langCode: 'en-GB'},
    {lang: 'English (United States)', langCode: 'en-US'},
    {lang: 'Estonian (Estonia)', langCode: 'et-EE'},
    {lang: 'Filipino (Philippines)', langCode: 'fil-PH'},
    {lang: 'Finnish (Finland)', langCode: 'fi-FI'},
    {lang: 'French (Belgium)', langCode: 'fr-BE'},
    {lang: 'French (Canada)', langCode: 'fr-CA'},
    {lang: 'French (France)', langCode: 'fr-FR'},
    {lang: 'French (Switzerland)', langCode: 'fr-CH'},
    {lang: 'Galician (Spain)', langCode: 'gl-ES'},
    {lang: 'Georgian (Georgia)', langCode: 'ka-GE'},
    {lang: 'German (Austria)', langCode: 'de-AT'},
    {lang: 'German (Germany)', langCode: 'de-DE'},
    {lang: 'German (Switzerland)', langCode: 'de-CH'},
    {lang: 'Greek (Greece)', langCode: 'el-GR'},
    {lang: 'Gujarati (India)', langCode: 'gu-IN'},
    {lang: 'Hebrew (Israel)', langCode: 'iw-IL'},
    {lang: 'Hindi (India)', langCode: 'hi-IN'},
    {lang: 'Hungarian (Hungary)', langCode: 'hu-HU'},
    {lang: 'Icelandic (Iceland)', langCode: 'is-IS'},
    {lang: 'Indonesian (Indonesia)', langCode: 'id-ID'},
    {lang: 'Italian (Italy)', langCode: 'it-IT'},
    {lang: 'Italian (Switzerland)', langCode: 'it-CH'},
    {lang: 'Japanese (Japan)', langCode: 'ja-JP'},
    {lang: 'Javanese (Indonesia)', langCode: 'jv-ID'},
    {lang: 'Kannada (India)', langCode: 'kn-IN'},
    {lang: 'Khmer (Cambodia)', langCode: 'km-KH'},
    {lang: 'Korean (South Korea)', langCode: 'ko-KR'},
    {lang: 'Lao (Laos)', langCode: 'lo-LA'},
    {lang: 'Latvian (Latvia)', langCode: 'lv-LV'},
    {lang: 'Lithuanian (Lithuania)', langCode: 'lt-LT'},
    {lang: 'Macedonian (North Macedonia)', langCode: 'mk-MK'},
    {lang: 'Malay (Malaysia)', langCode: 'ms-MY'},
    {lang: 'Malayalam (India)', langCode: 'ml-IN'},
    {lang: 'Marathi (India)', langCode: 'mr-IN'},
    {lang: 'Mongolian (Mongolia)', langCode: 'mn-MN'},
    {lang: 'Nepali (Nepal)', langCode: 'ne-NP'},
    {lang: 'Norwegian Bokmål (Norway)', langCode: 'no-NO'},
    {lang: 'Persian (Iran)', langCode: 'fa-IR'},
    {lang: 'Polish (Poland)', langCode: 'pl-PL'},
    {lang: 'Portuguese (Brazil)', langCode: 'pt-BR'},
    {lang: 'Portuguese (Portugal)', langCode: 'pt-PT'},
    {lang: 'Punjabi (Gurmukhi India)', langCode: 'pa-Guru-IN'},
    {lang: 'Romanian (Romania)', langCode: 'ro-RO'},
    {lang: 'Russian (Russia)', langCode: 'ru-RU'},
    {lang: 'Serbian (Serbia)', langCode: 'sr-RS'},
    {lang: 'Sinhala (Sri Lanka)', langCode: 'si-LK'},
    {lang: 'Slovak (Slovakia)', langCode: 'sk-SK'},
    {lang: 'Slovenian (Slovenia)', langCode: 'sl-SI'},
    {lang: 'Spanish (Argentina)', langCode: 'es-AR'},
    {lang: 'Spanish (Bolivia)', langCode: 'es-BO'},
    {lang: 'Spanish (Chile)', langCode: 'es-CL'},
    {lang: 'Spanish (Colombia)', langCode: 'es-CO'},
    {lang: 'Spanish (Costa Rica)', langCode: 'es-CR'},
    {lang: 'Spanish (Dominican Republic)', langCode: 'es-DO'},
    {lang: 'Spanish (Ecuador)', langCode: 'es-EC'},
    {lang: 'Spanish (El Salvador)', langCode: 'es-SV'},
    {lang: 'Spanish (Guatemala)', langCode: 'es-GT'},
    {lang: 'Spanish (Honduras)', langCode: 'es-HN'},
    {lang: 'Spanish (Mexico)', langCode: 'es-MX'},
    {lang: 'Spanish (Nicaragua)', langCode: 'es-NI'},
    {lang: 'Spanish (Panama)', langCode: 'es-PA'},
    {lang: 'Spanish (Paraguay)', langCode: 'es-PY'},
    {lang: 'Spanish (Peru)', langCode: 'es-PE'},
    {lang: 'Spanish (Puerto Rico)', langCode: 'es-PR'},
    {lang: 'Spanish (Spain)', langCode: 'es-ES'},
    {lang: 'Spanish (United States)', langCode: 'es-US'},
    {lang: 'Spanish (Uruguay)', langCode: 'es-UY'},
    {lang: 'Spanish (Venezuela)', langCode: 'es-VE'},
    {lang: 'Sundanese (Indonesia)', langCode: 'su-ID'},
    {lang: 'Swahili (Kenya)', langCode: 'sw-KE'},
    {lang: 'Swahili (Tanzania)', langCode: 'sw-TZ'},
    {lang: 'Swedish (Sweden)', langCode: 'sv-SE'},
    {lang: 'Tamil (India)', langCode: 'ta-IN'},
    {lang: 'Tamil (Malaysia)', langCode: 'ta-MY'},
    {lang: 'Tamil (Singapore)', langCode: 'ta-SG'},
    {lang: 'Tamil (Sri Lanka)', langCode: 'ta-LK'},
    {lang: 'Telugu (India)', langCode: 'te-IN'},
    {lang: 'Thai (Thailand)', langCode: 'th-TH'},
    {lang: 'Turkish (Turkey)', langCode: 'tr-TR'},
    {lang: 'Ukrainian (Ukraine)', langCode: 'uk-UA'},
    {lang: 'Urdu (India)', langCode: 'ur-IN'},
    {lang: 'Urdu (Pakistan)', langCode: 'ur-PK'},
    {lang: 'Uzbek (Uzbekistan)', langCode: 'uz-UZ'},
    {lang: 'Vietnamese (Vietnam)', langCode: 'vi-VN'},
    {lang: 'Zulu (South Africa)', langCode: 'zu-ZA'},
];

var translateLangs = [
    {lang: 'Afrikaans', langCode: 'af'},
    {lang: 'Albanian', langCode: 'sq'},
    {lang: 'Amharic', langCode: 'am'},
    {lang: 'Arabic', langCode: 'ar'},
    {lang: 'Armenian', langCode: 'hy'},
    {lang: 'Azerbaijani', langCode: 'az'},
    {lang: 'Basque', langCode: 'eu'},
    {lang: 'Belarusian', langCode: 'be'},
    {lang: 'Bengali', langCode: 'bn'},
    {lang: 'Bosnian', langCode: 'bs'},
    {lang: 'Bulgarian', langCode: 'bg'},
    {lang: 'Catalan', langCode: 'ca'},
    {lang: 'Cebuano', langCode: 'ceb (ISO-639-2)'},
    {lang: 'Chinese (Simplified)', langCode: 'zh-CN'},
    {lang: 'Chinese (Traditional)', langCode: 'zh-TW'},
    {lang: 'Corsican', langCode: 'co'},
    {lang: 'Croatian', langCode: 'hr'},
    {lang: 'Czech', langCode: 'cs'},
    {lang: 'Danish', langCode: 'da'},
    {lang: 'Dutch', langCode: 'nl'},
    {lang: 'English', langCode: 'en'},
    {lang: 'Esperanto', langCode: 'eo'},
    {lang: 'Estonian', langCode: 'et'},
    {lang: 'Finnish', langCode: 'fi'},
    {lang: 'French', langCode: 'fr'},
    {lang: 'Frisian', langCode: 'fy'},
    {lang: 'Galician', langCode: 'gl'},
    {lang: 'Georgian', langCode: 'ka'},
    {lang: 'German', langCode: 'de'},
    {lang: 'Greek', langCode: 'el'},
    {lang: 'Gujarati', langCode: 'gu'},
    {lang: 'Haitian Creole', langCode: 'ht'},
    {lang: 'Hausa', langCode: 'ha'},
    {lang: 'Hawaiian', langCode: 'haw'},
    {lang: 'Hebrew', langCode: 'he'},
    {lang: 'Hindi', langCode: 'hi'},
    {lang: 'Hmong', langCode: 'hmn'},
    {lang: 'Hungarian', langCode: 'hu'},
    {lang: 'Icelandic', langCode: 'is'},
    {lang: 'Igbo', langCode: 'ig'},
    {lang: 'Indonesian', langCode: 'id'},
    {lang: 'Irish', langCode: 'ga'},
    {lang: 'Italian', langCode: 'it'},
    {lang: 'Japanese', langCode: 'ja'},
    {lang: 'Javanese', langCode: 'jv'},
    {lang: 'Kannada', langCode: 'kn'},
    {lang: 'Kazakh', langCode: 'kk'},
    {lang: 'Khmer', langCode: 'km'},
    {lang: 'Kinyarwanda', langCode: 'rw'},
    {lang: 'Korean', langCode: 'ko'},
    {lang: 'Kurdish', langCode: 'ku'},
    {lang: 'Kyrgyz', langCode: 'ky'},
    {lang: 'Lao', langCode: 'lo'},
    {lang: 'Latin', langCode: 'la'},
    {lang: 'Latvian', langCode: 'lv'},
    {lang: 'Lithuanian', langCode: 'lt'},
    {lang: 'Luxembourgish', langCode: 'lb'},
    {lang: 'Macedonian', langCode: 'mk'},
    {lang: 'Malagasy', langCode: 'mg'},
    {lang: 'Malay', langCode: 'ms'},
    {lang: 'Malayalam', langCode: 'ml'},
    {lang: 'Maltese', langCode: 'mt'},
    {lang: 'Maori', langCode: 'mi'},
    {lang: 'Marathi', langCode: 'mr'},
    {lang: 'Mongolian', langCode: 'mn'},
    {lang: 'Myanmar (Burmese)', langCode: 'my'},
    {lang: 'Nepali', langCode: 'ne'},
    {lang: 'Norwegian', langCode: 'no'},
    {lang: 'Nyanja (Chichewa)', langCode: 'ny'},
    {lang: 'Odia (Oriya)', langCode: 'or'},
    {lang: 'Pashto', langCode: 'ps'},
    {lang: 'Persian', langCode: 'fa'},
    {lang: 'Polish', langCode: 'pl'},
    {lang: 'Portuguese (Portugal, Brazil)', langCode: 'pt'},
    {lang: 'Punjabi', langCode: 'pa'},
    {lang: 'Romanian', langCode: 'ro'},
    {lang: 'Russian', langCode: 'ru'},
    {lang: 'Samoan', langCode: 'sm'},
    {lang: 'Scots Gaelic', langCode: 'gd'},
    {lang: 'Serbian', langCode: 'sr'},
    {lang: 'Sesotho', langCode: 'st'},
    {lang: 'Shona', langCode: 'sn'},
    {lang: 'Sindhi', langCode: 'sd'},
    {lang: 'Sinhala (Sinhalese)', langCode: 'si'},
    {lang: 'Slovak', langCode: 'sk'},
    {lang: 'Slovenian', langCode: 'sl'},
    {lang: 'Somali', langCode: 'so'},
    {lang: 'Spanish', langCode: 'es'},
    {lang: 'Sundanese', langCode: 'su'},
    {lang: 'Swahili', langCode: 'sw'},
    {lang: 'Swedish', langCode: 'sv'},
    {lang: 'Tagalog (Filipino)', langCode: 'tl'},
    {lang: 'Tajik', langCode: 'tg'},
    {lang: 'Tamil', langCode: 'ta'},
    {lang: 'Tatar', langCode: 'tt'},
    {lang: 'Telugu', langCode: 'te'},
    {lang: 'Thai', langCode: 'th'},
    {lang: 'Turkish', langCode: 'tr'},
    {lang: 'Turkmen', langCode: 'tk'},
    {lang: 'Ukrainian', langCode: 'uk'},
    {lang: 'Urdu', langCode: 'ur'},
    {lang: 'Uyghur', langCode: 'ug'},
    {lang: 'Uzbek', langCode: 'uz'},
    {lang: 'Vietnamese', langCode: 'vi'},
    {lang: 'Welsh', langCode: 'cy'},
    {lang: 'Xhosa', langCode: 'xh'},
    {lang: 'Yiddish', langCode: 'yi'},
    {lang: 'Yoruba', langCode: 'yo'},
    {lang: 'Zulu', langCode: 'zu'},
];